### ISSUE TITLE
NA PA - Plugin Opening

### ISSUE THREAD

**Issue by DelphinoVarela** [ST3AM-US/st3am-com-issues#1]
**Affected Plugin**
VAL-FORM

**Describe the bug**

**To Reproduce**
1. Search apptNumber 864926
2. Click on Validate Form button

**Current behavior**
Plugin isn't opening, the loading circle is displayed on the middle of the screen

**Expected behavior**
Plugin should open and display some information

**Screenshots**
https://drive.google.com/file/d/1XxbzO3ABRNl-INkuPunDun7U0cIQZkt9/view?usp=share_link

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by mm-catdev** [comment]
We have realized that the activity is a multi-day non-scheduled. The segments of a multi-day activity are created when you are assigning that activity to the route. Is is expected to have this scenario  ? A multi-day activity non-scheduled that requires the plugin to update the Service Requests , etc ?

**Comment by DelphinoVarela** [comment]
Multiday isn't right now mandatory. But in phase 2 of the project activities must be multiday.
Yes I played with the 1st multiday activity (I completed one segment).

I created the apptNumber : 865043

**Comment by mm-catdev** [comment]
the most important thing : is it possible to have a multiday activity non-scheduled, and expect the technician to be able to send Service Requests and open the plugin ? Because this is the case that is creating the issue.

A multiday activity non-scheduled has not created the segment yet, so, it is a challenge for the plugin to open it as an activity.

Regards

**Comment by DelphinoVarela** [comment]
My expectation was to to have a multiday activity non-scheduled...

I will find a "solution".
