### ISSUE TITLE
VE FR - st3am-etl-1.2 - Enhancement - Inbound archive change

### ISSUE THREAD

**Issue by DelphinoVarela** [ST3AM-US/st3am-com-issues#27]
**Is your feature request related to a problem? Please describe.**
It's a Verisure Spain IT requirement not provided earlier.

**Describe the solution you'd like**
A processed Inbound xml file should be:
- archive on the sftp in the following path "/files/3PL/ShipmentRequest/Outbound/HIST/VDIYFR" (variable)
- the archive name should have a sufix : _YYYYMMDDmmss (timestamp of the processing).

Exemple:
- Incoming file : INT001SCMS05_ShipReq_ORA_VDIYFR_71802055_20230913112342.xml
- Archived file : INT001SCMS05_ShipReq_ORA_VDIYFR_71802055_20230913112342_20230915150923.xml

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by mm-catdev** [comment]
Design document modified with this requirement

**Comment by be-ant** [comment]
Confirmed that customer accepts the timestamp format in YYYMMDDTHHMMSS format

**Comment by DelphinoVarela** [comment]
Tested okay

**Comment by DelphinoVarela** [comment]
Minor issue related with the suffix.

1- A file has been archived as : INT001SCMS05_ShipReq_ORA_VDIYFR_71809848_20230919075455_**20230919T075000**.xml
2- it should have been archived as : 
INT001SCMS05_ShipReq_ORA_VDIYFR_71809848_20230919075455_**20230919T075513**.xml

In the logs I'm seeing a difference between the value of execution_date and start_date

Logs : 
[2023-09-19, 09:55:13 CEST] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=st3am-verisure-inbound, task_id=remove_data_from_SFTP, execution_date=20230919T075000, start_date=20230919T075513, end_date=20230919T075513

**Comment by mm-catdev** [comment]
I don't understand the issue. 
We understood that a timestamp was requested to be included as a suffix to the file.  Why should be the start date and not the execution date?

**Comment by mm-catdev** [comment]
BTW, the sufix used today is also the same id that will allow you to identify the DAG execution ( dag_id ). So, we really recommend using this one, unless there is a business reason for using something else.

**Comment by be-ant** [comment]
The reason for this is the way Airflow manages the intervals (see #28). We use a variable called `{{ ts_nodash }}` that represents what is called the logical date (see https://airflow.apache.org/docs/apache-airflow/stable/templates-ref.html). 
 (Logical Date: The start of the data interval. It does not represent when the DAG will be executed. Before Airflow 2.2, this was referred to as the execution date.). This is kept during all the lifetime of the dag run, no matter how often a  task is executed, cleared, executed again, creating a link between all the files generated during a run.

Using instead a `now()` or similar has a potential issue: if the customer has to re-execute a task because of errors then the link is lost, and there is no more a connection between all the files.

I can offer an alternative that may provide all we need without losing the tracking: naming the FINAL file (the one deposited in the SFTP server with the current name plus a`now()` prefix

Example: 

1. DAG run for the interval 0400 - 0405 gets executed at 040520. Reads file PREFIX.xml

2. The file returned in the archive will be PREFIX_040000_040520.xml

**Comment by DelphinoVarela** [comment]
> I don't understand the issue. We understood that a timestamp was requested to be included as a suffix to the file. Why should be the start date and not the execution date?

There's 5 minutes difference between each (start date / execution date). This suffix will be used only for troubleshooting : it can confuse the analysis.

I won't fight about it because I have other battles (Verisure Spain IT opened an issue about Outbound structure. I'm waiting a confirmation before creating a ticket)
